echo 'Delete directory "~/vim_share"...';
rm -rf ~/vim_share;
echo 'Delete directory "~/.vimperator/vimperator-plugins"...';
rm -rf ~/.vimperator/vimperator-plugins;
echo 'Delete "~/_vimrc" or "~/.vimrc"...';
rm -i ~/_vimrc;
rm -i ~/.vimrc;
echo 'Delete "~/_gvimrc" or "~/.gvimrc"...';
rm -i ~/_gvimrc;
rm -i ~/.gvimrc;
echo 'Delete "~/_vimperatorrc" or "~/.vimperatorrc"...';
rm -i ~/_vimperatorrc;
rm -i ~/.vimperatorrc;
echo 'Delete "~/_zshrc" or "~/.zshrc"...';
rm -i ~/_zshrc;
rm -i ~/.zshrc;
echo 'Delete "~/_tmux.conf" or "~/.tmux.conf"...';
rm -i ~/_tmux.conf;
rm -i ~/.tmux.conf;
echo 'Delete "~/site_vimrc"...';
rm -i ~/site_vimrc;
echo 'Delete "~/site_gvimrc"...';
rm -i ~/site_gvimrc;
echo 'Delete "~/site_vimperatorrc"...';
rm -i ~/site_vimperatorrc;
echo 'Delete "~/site_zshrc"...';
rm -i ~/site_zshrc;
echo 'Delete "~/site_tmux_conf"...';
rm -i ~/site_tmux_conf;
echo 'Finished!';
