echo 'Delete directory "~/vim_share"...';
rm -rf ~/vim_share;
echo 'Delete "~/_vimrc" or "~/.vimrc"...';
rm ~/_vimrc;
rm ~/.vimrc;
echo 'Delete "~/_gvimrc" or "~/.gvimrc"...';
rm ~/_gvimrc;
rm ~/.gvimrc;
echo 'Delete "~/site_vimrc"...';
rm -i ~/site_vimrc;
echo 'Delete "~/site_gvimrc"...';
rm -i ~/site_gvimrc;
echo 'Finished!';
